### PR TITLE
Prep 0.4.0 release.

### PR DESCRIPTION
**Pull request by hjoliver**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hjoliver** [comment]
(Build will fail until cylc-flow 8.0b1 is on conda forge)

**Review by kinow — APPROVED** [review]
Checked version, build, and hash. All looking good :+1:

**Comment by hjoliver** [comment]
@conda-forge-admin, please rerender

**Comment by hjoliver** [comment]
@conda-forge-admin, please rerender

**Comment by hjoliver** [comment]
Tests now passing; one approval will do for this.

**Pull request merged**
